// apps/desktop/src/renderer/features/settings/SettingsPage.tsx
// Settings page. Renders
// the settings sections top-to-bottom (Permissions is macOS-only) inside
// the .settings-flow / .settings-section layout. Each section's body is a
// self-contained panel under ./panels/. Model engine wiring now lives on Models.

import { PageHeader } from "../../shared/ui/primitives/PageHeader";
import { useT } from "../../i18n/context";
import {
  SETTINGS_SECTION_LABEL_KEY,
  isMacOS,
  type SettingsSection,
} from "./panels/constants";
import { PermissionPanel } from "./panels/PermissionPanel";
import { MicrophonePanel } from "./panels/MicrophonePanel";
import { NetworkPanel } from "./panels/NetworkPanel";
import { GeneralPanel } from "./panels/GeneralPanel";
import { AboutPanel } from "./panels/AboutPanel";
import "./panels/settings.css";

function Section({
  section,
  label,
  action,
  children,
}: {
  section: SettingsSection;
  label: string;
  action?: React.ReactNode;
  children: React.ReactNode;
}): JSX.Element {
  return (
    <section className="settings-section" data-section={section}>
      <header className="settings-section-head">
        <h2>{label}</h2>
        {action ?? null}
      </header>
      <div className="settings-section-body">
        {children}
      </div>
    </section>
  );
}

export function SettingsPage(): JSX.Element {
  const t = useT();
  const showPermissions = isMacOS();
  const label = (section: SettingsSection): string =>
    t(SETTINGS_SECTION_LABEL_KEY[section]);

  return (
    <section className="page settings-page">
      <div className="settings-flow">
        <div className="settings-flow-content">
          <PageHeader title={t("settings.page.title")} />

          {showPermissions ? (
            <Section section="Permissions" label={label("Permissions")}>
              <PermissionPanel />
            </Section>
          ) : null}

          <Section section="Microphone" label={label("Microphone")}>
            <MicrophonePanel />
          </Section>

          <Section section="Network" label={label("Network")}>
            <NetworkPanel />
          </Section>

          <Section section="General" label={label("General")}>
            <GeneralPanel />
          </Section>

          <Section section="About" label={label("About")}>
            <AboutPanel />
          </Section>
        </div>
      </div>
    </section>
  );
}

// apps/desktop/src/features/settings/SettingsPage.svelte
<script lang="ts">
  import PageHeader from "../../shared/ui/PageHeader.svelte";
  import { SETTINGS_SECTIONS, SETTINGS_SECTION_LABEL_KEY, type SettingsSection } from "./constants";
  import AboutSettings from "./AboutSettings.svelte";
  import AppearanceLanguageSettings from "./AppearanceLanguageSettings.svelte";
  import Engine from "./Engine.svelte";
  import MicrophoneSettings from "./MicrophoneSettings.svelte";
  import NetworkSettings from "./NetworkSettings.svelte";
  import PermissionSettings from "./PermissionSettings.svelte";
  import { isMacOS } from "../../app/platform";
  import { t } from "../../i18n";

  const showPermissions = isMacOS();

  const labels = $derived<Record<SettingsSection, string>>(
    Object.fromEntries(
      SETTINGS_SECTIONS.map((s) => [s, $t(SETTINGS_SECTION_LABEL_KEY[s])])
    ) as Record<SettingsSection, string>
  );
</script>

<main class="page settings-page">
  <div class="settings-flow">
    <div class="settings-flow-content">
      <PageHeader title={$t("settings.page.title")} />

      {#if showPermissions}
        <section class="settings-section">
          <header class="settings-section-head">
            <span class="settings-section-mark">—</span>
            <h2>{labels.Permissions}</h2>
          </header>
          <PermissionSettings />
        </section>
      {/if}

      <section class="settings-section">
        <header class="settings-section-head">
          <span class="settings-section-mark">—</span>
          <h2>{labels.Microphone}</h2>
        </header>
        <MicrophoneSettings />
      </section>

      <section class="settings-section">
        <header class="settings-section-head">
          <span class="settings-section-mark">—</span>
          <h2>{labels.Engine}</h2>
        </header>
        <Engine />
      </section>

      <section class="settings-section">
        <header class="settings-section-head">
          <span class="settings-section-mark">—</span>
          <h2>{labels["Network"]}</h2>
        </header>
        <NetworkSettings />
      </section>

      <section class="settings-section">
        <header class="settings-section-head">
          <span class="settings-section-mark">—</span>
          <h2>{labels["Appearance & Language"]}</h2>
        </header>
        <AppearanceLanguageSettings />
      </section>

      <section class="settings-section">
        <header class="settings-section-head">
          <span class="settings-section-mark">—</span>
          <h2>{labels.About}</h2>
        </header>
        <AboutSettings />
      </section>
    </div>
  </div>
</main>
