// apps/desktop/src/renderer/shared/ui/layout/Sidebar.tsx
import { NavIcon } from "../primitives/NavIcon";
import { SotoMark } from "../primitives/SotoMark";
import { UtilIcon } from "../primitives/UtilIcon";
import { NAV_LABEL_KEY, type NavItem } from "../../nav";
import { themeIconName } from "../../theme";
import { LOCALE_REGISTRY } from "../../../i18n/types";
import { useT } from "../../../i18n/context";
import { useAppStore, useTheme, useView } from "../../../store/appStore";

const PRIMARY: NavItem[] = ["Home", "History", "Modes", "Dictionary", "Models"];

export function Sidebar(): JSX.Element {
  const t = useT();
  const active = useView();
  const setView = useAppStore((s) => s.setView);
  const theme = useTheme();
  const cycleTheme = useAppStore((s) => s.cycleTheme);
  const locale = useAppStore((s) => s.locale);
  const cycleLocale = useAppStore((s) => s.cycleLocale);
  const localeLabel = locale === "system" ? "System" : LOCALE_REGISTRY[locale].nativeName;

  return (
    <aside className="sidebar">
      <div className="sidebar-mark">
        <SotoMark size={28} />
        <span className="sidebar-wordmark">Soto</span>
      </div>
      <nav className="nav" aria-label="Primary">
        {PRIMARY.map((item) => (
          <button
            key={item}
            type="button"
            className={active === item ? "active" : ""}
            aria-current={active === item ? "page" : undefined}
            onClick={() => setView(item)}
          >
            <NavIcon name={item} />
            <span>{t(NAV_LABEL_KEY[item])}</span>
          </button>
        ))}
      </nav>
      <nav className="nav nav-secondary" aria-label="Secondary">
        <button
          type="button"
          className={active === "Settings" ? "active" : ""}
          aria-current={active === "Settings" ? "page" : undefined}
          onClick={() => setView("Settings")}
        >
          <NavIcon name="Settings" />
          <span>{t(NAV_LABEL_KEY.Settings)}</span>
        </button>
      </nav>
      <div className="sidebar-spacer" />
      <div className="util-row">
        <button
          type="button"
          className="util-btn"
          aria-label={t("sidebar.helpAria")}
          onClick={() => setView("Settings")}
        >
          <UtilIcon name="help" />
        </button>
        <button
          type="button"
          className="util-btn"
          aria-label={t("sidebar.feedbackAria")}
          onClick={() => setView("Settings")}
        >
          <UtilIcon name="chat" />
        </button>
        <button
          type="button"
          className="util-btn"
          aria-label={t("sidebar.themeAria", { theme })}
          onClick={cycleTheme}
        >
          <UtilIcon name={themeIconName(theme)} />
        </button>
        <button
          type="button"
          className="util-btn"
          aria-label={t("sidebar.languageAria", { language: localeLabel })}
          onClick={cycleLocale}
        >
          <UtilIcon name="globe" />
        </button>
      </div>
    </aside>
  );
}

// apps/desktop/src/app/Sidebar.svelte
<script lang="ts">
  import NavIcon from "../shared/ui/NavIcon.svelte";
  import SotoMark from "../shared/ui/SotoMark.svelte";
  import UtilIcon from "../shared/ui/UtilIcon.svelte";
  import { NAV_LABEL_KEY, type NavItem } from "../shared/nav";
  import { nextTheme, themeIconName, type Theme } from "../shared/theme";
  import { t } from "../i18n";

  let { active, onSelect }: { active: NavItem; onSelect: (item: NavItem) => void } = $props();

  const primary: NavItem[] = ["Home", "History", "Dictionary", "Modes"];
  let theme = $state<Theme>("system");

  $effect(() => {
    document.documentElement.setAttribute("data-theme", theme);
  });

  function cycleTheme() {
    theme = nextTheme(theme);
  }
</script>

<aside class="sidebar">
  <div class="brand brand-italic">
    <SotoMark size={28} />
    <span class="brand-word">Soto</span>
  </div>
  <nav class="nav" aria-label="Primary">
    {#each primary as item (item)}
      <button
        type="button"
        class={active === item ? "active" : ""}
        onclick={() => onSelect(item)}
      >
        <NavIcon name={item} />
        <span>{$t(NAV_LABEL_KEY[item])}</span>
      </button>
    {/each}
  </nav>
  <div class="sidebar-divider"></div>
  <nav class="nav nav-secondary" aria-label="Secondary">
    <button
      type="button"
      class={active === "Settings" ? "active" : ""}
      onclick={() => onSelect("Settings")}
    >
      <NavIcon name="Settings" />
      <span>{$t(NAV_LABEL_KEY.Settings)}</span>
    </button>
  </nav>
  <div class="sidebar-spacer"></div>
  <div class="util-row">
    <button type="button" class="util-btn" aria-label={$t("sidebar.helpAria")} onclick={() => onSelect("Settings")}>
      <UtilIcon name="help" />
    </button>
    <button type="button" class="util-btn" aria-label={$t("sidebar.feedbackAria")} onclick={() => onSelect("Settings")}>
      <UtilIcon name="chat" />
    </button>
    <button type="button" class="util-btn" aria-label={$t("sidebar.themeAria", { theme })} onclick={cycleTheme}>
      <UtilIcon name={themeIconName(theme)} />
    </button>
  </div>
</aside>
