// apps/desktop/src/shared/ui/PageFilterRow.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  export type PageFilterMarker = "ok" | "auto" | "manual";

  export type FilterPill = {
    id: string;
    label: string;
    count?: number;
    marker?: PageFilterMarker;
  };

  let {
    pills,
    activeId,
    onSelect,
    actions
  }: {
    pills: FilterPill[];
    activeId: string;
    onSelect: (id: string) => void;
    actions?: Snippet;
  } = $props();
</script>

<div class="page-filter-row">
  <div class="page-filter-pills" role="tablist">
    {#each pills as pill (pill.id)}
      {@const active = activeId === pill.id}
      <button
        type="button"
        role="tab"
        aria-selected={active}
        class={`page-filter-pill${active ? " active" : ""}`}
        onclick={() => onSelect(pill.id)}
      >
        {#if pill.marker === "ok"}
          <span class="dot dot-ok" aria-hidden="true"></span>
        {:else if pill.marker === "auto"}
          <span class={`word-mark word-mark-${pill.marker}`} aria-hidden="true"></span>
        {:else if pill.marker === "manual"}
          <span class={`word-mark word-mark-${pill.marker}`} aria-hidden="true"></span>
        {/if}
        <span>{pill.label}</span>
        {#if pill.count !== undefined}
          <span class="page-filter-pill-count">{pill.count}</span>
        {/if}
      </button>
    {/each}
  </div>
  <div class="page-filter-actions">
    {#if actions}
      {@render actions()}
    {/if}
  </div>
</div>

// apps/desktop/src/renderer/shared/ui/primitives/PageFilterRow.tsx
import { type ReactNode } from "react";

import { useT } from "../../../i18n/context";

export type PageFilterMarker = "ok" | "auto" | "manual";

export interface FilterPill {
  id: string;
  label: string;
  count?: number;
  marker?: PageFilterMarker;
}

export function PageFilterRow({
  pills,
  activeId,
  onSelect,
  actions,
  groupLabel,
}: {
  pills: FilterPill[];
  activeId: string;
  onSelect: (id: string) => void;
  actions?: ReactNode;
  /** Accessible name for the filter group. Defaults to t("common.filters"). */
  groupLabel?: string;
}): JSX.Element {
  const t = useT();
  return (
    <div className="page-filter-row">
      <div className="page-filter-pills" role="group" aria-label={groupLabel ?? t("common.filters")}>
        {pills.map((pill) => {
          const active = activeId === pill.id;
          return (
            <button
              key={pill.id}
              type="button"
              aria-pressed={active}
              className={`page-filter-pill${active ? " active" : ""}`}
              onClick={() => onSelect(pill.id)}
            >
              {pill.marker === "ok" ? (
                <span className="dot dot-ok" aria-hidden="true" />
              ) : pill.marker === "auto" ? (
                <span className="word-mark word-mark-auto" aria-hidden="true" />
              ) : pill.marker === "manual" ? (
                <span className="word-mark word-mark-manual" aria-hidden="true" />
              ) : null}
              <span>{pill.label}</span>
              {pill.count !== undefined ? (
                <span className="page-filter-pill-count">{pill.count}</span>
              ) : null}
            </button>
          );
        })}
      </div>
      <div className="page-filter-actions">{actions}</div>
    </div>
  );
}
