// apps/desktop/src/renderer/shared/ui/primitives/PageHeader.tsx
export function PageHeader({
  kicker,
  title,
  sub,
}: {
  kicker?: string;
  title: string;
  sub?: string;
}): JSX.Element {
  return (
    <header className="page-header">
      {kicker ? <div className="kicker">{kicker}</div> : null}
      <div className="title-line">
        <h1>{title}</h1>
      </div>
      {sub ? <p>{sub}</p> : null}
    </header>
  );
}

// apps/desktop/src/shared/ui/PageHeader.svelte
<script lang="ts">
  let {
    kicker,
    title,
    sub
  }: { kicker?: string; title: string; sub?: string } = $props();
</script>

<header class="page-header">
  {#if kicker}<div class="kicker">{kicker}</div>{/if}
  <div class="title-line">
    <h1>{title}</h1>
  </div>
  {#if sub}<p>{sub}</p>{/if}
</header>
